server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_micro
    username: root
    password: Welcome@23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0